# Generated by Django 3.1 on 2020-08-21 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flower', '0003_auto_20200821_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='fifth_name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='image',
            name='fifth_value',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='image',
            name='first_value',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='image',
            name='fourth_name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='image',
            name='fourth_value',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='image',
            name='second_name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='image',
            name='second_value',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='image',
            name='third_name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='image',
            name='third_value',
            field=models.FloatField(default=0),
        ),
    ]
