# Generated by Django 3.1 on 2020-08-22 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flower', '0005_auto_20200822_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='fifth_value',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='image',
            name='first_value',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='image',
            name='fourth_value',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='image',
            name='second_value',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='image',
            name='third_value',
            field=models.FloatField(),
        ),
    ]
